/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';
// // 获取角色
// const role = JSON.parse(localStorage.getItem('userInfo') ?? '{}')?.role;
// // ✅ 正确写法
// const isRepairRole = role === '维修人员';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'faults',
    path: '/faults',
    component: 'layout.base$view.faults',
    meta: {
      title: 'faults',
      i18nKey: 'route.faults',
      icon: 'mdi:alert-circle-outline',
      order: 4
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'miningsite',
    path: '/miningsite',
    component: 'layout.base$view.miningsite',
    meta: {
      title: 'miningsite',
      i18nKey: 'route.miningsite',
      icon: 'mdi:factory',
      order: 2,
      role: [1, 2, 3]
    }
  },
  {
    name: 'repairrecords',
    path: '/repairrecords',
    component: 'layout.base$view.repairrecords',
    meta: {
      title: 'repairrecords',
      i18nKey: 'route.repairrecords',
      icon: 'mdi:file-cog',
      order: 5,
      role: [1, 2, 3, 4]
    },
    props: true
  },
  {
    name: 'repairrecordsdetail',
    path: '/repairrecords/:id/detail',
    component: 'layout.base$view.repairrecordsdetail',
    meta: {
      title: '维修详情',
      i18nKey: 'route.repairrecordsdetail',
      props: true,
      hideInMenu: true,
      role: [1, 2, 3, 4]
    },
    props: true
  },
  {
    name: 'repairstation',
    path: '/repairstation',
    component: 'layout.base$view.repairstation',
    meta: {
      title: 'repairstation',
      i18nKey: 'route.repairstation',
      icon: 'mdi:office-building-cog',
      order: 6,
      role: [1, 2, 3, 4]
    }
  },
  {
    name: 'sitedetail',
    path: '/miningsite/:id/info',
    component: 'layout.base$view.sitedetail',
    meta: {
      title: 'sitedetail',
      i18nKey: 'route.sitedetail',
      props: true,
      hideInMenu: true,
      role: [1, 2, 3]
    },
    props: true
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      icon: 'mdi:lock',
      order: 7,
      role: [1, 2, 3]
    }
  },
  {
    name: 'workflow',
    path: '/workflow',
    component: 'layout.base$view.workflow',
    meta: {
      title: 'workflow',
      i18nKey: 'route.workflow',
      icon: 'mdi:flowchart',
      order: 3,
      role: [1, 2, 3]
    }
  }
];
