/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';
// // 获取角色
// const role = JSON.parse(localStorage.getItem('userInfo') ?? '{}')?.role;
// // ✅ 正确写法
// const isRepairRole = role === '维修人员';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'faults',
    path: '/faults',
    component: 'layout.base$view.faults',
    meta: {
      title: 'faults',
      i18nKey: 'route.faults',
      icon: 'mdi:alert-circle-outline',
      order: 40,
      roles: ['1', '2', '3', '5']
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 10,
      roles: ['1', '2', '5']
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'miningsite',
    path: '/miningsite',
    component: 'layout.base$view.miningsite',
    meta: {
      title: 'miningsite',
      i18nKey: 'route.miningsite',
      icon: 'mdi:factory',
      order: 20,
      roles: ['1', '2', '3', '5']
    }
  },
  {
    name: 'repairrecords',
    path: '/repairrecords',
    component: 'layout.base$view.repairrecords',
    meta: {
      title: 'repairrecords',
      i18nKey: 'route.repairrecords',
      icon: 'mdi:file-cog',
      order: 50,
      roles: ['1', '2', '4', '5']
    },
    props: true
  },
  {
    name: 'repairrecordsdetail',
    path: '/repairrecords/:id/detail',
    component: 'layout.base$view.repairrecordsdetail',
    meta: {
      title: '维修详情',
      i18nKey: 'route.repairrecordsdetail',
      props: true,
      hideInMenu: true,
      roles: ['1', '2', '4', '5']
    },
    props: true
  },
  {
    name: 'repairreport',
    path: '/repairreport',
    component: 'layout.base$view.repairreport',
    meta: {
      title: 'repairreport',
      i18nKey: 'route.repairreport',
      icon: 'mdi:file-document-outline',
      order: 15,
      roles: ['1', '2', '5']
    }
  },
  {
    name: 'repairstation',
    path: '/repairstation',
    component: 'layout.base$view.repairstation',
    meta: {
      title: 'repairstation',
      i18nKey: 'route.repairstation',
      icon: 'mdi:office-building-cog',
      order: 60,
      roles: ['1', '2', '5']
    }
  },
  {
    name: 'scrapmachine',
    path: '/scrapmachine',
    component: 'layout.base$view.scrapmachine',
    meta: {
      title: 'scrapmachine',
      i18nKey: 'route.scrapmachine',
      icon: 'mdi:trash-can-outline',
      order: 55,
      roles: ['1', '2', '5']
    }
  },
  {
    name: 'sitedetail',
    path: '/miningsite/:id/info',
    component: 'layout.base$view.sitedetail',
    meta: {
      title: 'sitedetail',
      i18nKey: 'route.sitedetail',
      props: true,
      hideInMenu: true,
      roles: ['1', '2', '3', '5']
    },
    props: true
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      hideInMenu: true
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      icon: 'mdi:lock',
      order: 70,
      roles: ['1', '2', '5']
    }
  },
  {
    name: 'workflow',
    path: '/workflow',
    component: 'layout.base$view.workflow',
    meta: {
      title: 'workflow',
      i18nKey: 'route.workflow',
      icon: 'mdi:flowchart',
      order: 30,
      roles: ['1', '2', '4', '5']
    }
  },
  {
    name: 'workflowdetail',
    path: '/workflowdetail/:id',
    component: 'layout.base$view.workflowdetail',
    meta: {
      title: '工单明细',
      hideInMenu: true,
      props: true,
      i18nKey: 'route.workflowdetail',
      roles: ['1', '2', '4', '5']
    },
    props: true
  }
];
